### ISSUE TITLE
LDAP SSL custom CA

### ISSUE THREAD

**Issue by engelant** [zokradonh/kopano-docker#407]
So I wanted to connect Kopano server to a test Samba4 instance, and at least the current samba versions won't let you bind without SSL/TLS.
After some research I got the idea to simply install my custom public CA cert on the docker host and add the folders to the container.
```console
root:~$ cp my-custom-ca.crt /usr/local/share/ca-certificates/
root:~$ update-ca-certificates
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```
Afterwards creating a new override file
#### **`docker-compose.override.yml`** 
``` yml
version: "3.5"

services:
  kopano_server:
    volumes:
      - /etc/ssl/certs/:/etc/ssl/certs/:ro
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/:ro
```
And including it in the `.env` *COMPOSE_FILE=* section.

I guess I propably will have to do that for the **tvial/docker-mailserver**, for SMTP/IMAP access, but I'll burn that bridge when I cross it.

Long story short, I would like to find a nice little place inside this repo, where to put this little bit of informtaion. Is the WiKi an option or is it not used for a good reason?

Furthermore one might want to enable STARTTLS for some reason instead of using the SSL port, but with the given *KCCONFIG_...* this seems to be impossible, since it makes everything lowercase.
