### ISSUE TITLE
imap not working with ldap demo?

### ISSUE THREAD

**Issue by mhoffmann75** [zokradonh/kopano-docker#97]
i want to add imap (for connecting macOS native mail.app) to the demo.

However all I get is this error from mail container, when trying to login via imap (e.g. thunderbird):
kopano dovecot: auth: Error: LDAP: Can't connect to server: ldap://ldap:389

I'm using demo ldap schema of this project and have changed docker-compose.yml to enable imap, export ports, temporary disable fail2ban and reuse lets encrypt certificate from web container (which isn't too pretty yet because of the hardcoded path, but thats another story) :

```
  mail:
    #image: tvial/docker-mailserver:release-v6.1.0
    image: tvial/docker-mailserver:latest
    restart: always
    hostname: kopano
    domainname: ${LDAP_DOMAIN}
    container_name: mail
    depends_on:
      - ldap
    ports: 
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - mtaconfig:/tmp/docker-mailserver/
      - web:/etc/letsencrypt:ro
    environment:
      - TZ=${TZ}
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/letsencrypt/acme/acme-v02.api.letsencrypt.org/sites/kopano.mydomain.de/kopano.mydomain.de.crt
      - SSL_KEY_PATH=/etc/letsencrypt/acme/acme-v02.api.letsencrypt.org/sites/kopano.mydomain.de/kopano.mydomain.de.key
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      #- SSL_TYPE=self-signed
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=${LDAP_SERVER}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PW=${LDAP_BIND_PW}
      - LDAP_QUERY_FILTER_USER=${LDAP_QUERY_FILTER_USER}
      - LDAP_QUERY_FILTER_GROUP=${LDAP_QUERY_FILTER_GROUP}
      - LDAP_QUERY_FILTER_ALIAS=${LDAP_QUERY_FILTER_ALIAS}
      - LDAP_QUERY_FILTER_DOMAIN=${LDAP_QUERY_FILTER_DOMAIN}
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_LDAP_SERVER=${LDAP_SERVER}
      - SASLAUTHD_LDAP_BIND_DN=${LDAP_BIND_DN}
      - SASLAUTHD_LDAP_PASSWORD=${LDAP_BIND_PW}
      - SASLAUTHD_LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - SASLAUTHD_LDAP_FILTER=${SASLAUTHD_LDAP_FILTER}
      - SASLAUTHD_MECHANISMS=ldap
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
      - SMTP_ONLY=0
      - PERMIT_DOCKER=host
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_DAGENT=lmtp:kopano_dagent:2003
      - REPORT_RECIPIENT=1
    env_file:
      - mail.env
    networks:
      - kopano-net
      - ldap-net
    #dns: 1.1.1.1 # using Google DNS can lead to lookup errors uncomment this option and 
    # set to the ip of a trusted dns service (Cloudflare is given as an example). 
    # See https://github.com/zokradonh/kopano-docker/issues/52 for more information.
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

Thunderbird does some autodetection and none of the attempts is successful - login with <user2@xxxx> cannot work. But the first attempt should work?

```
Mar  1 18:59:31 kopano dovecot: auth: Error: LDAP: Can't connect to server: ldap://ldap:389
Mar  1 18:59:37 kopano dovecot: auth: Error: LDAP: Can't connect to server: ldap://ldap:389
Mar  1 18:59:43 kopano dovecot: auth: Error: LDAP: Can't connect to server: ldap://ldap:389
Mar  1 18:59:45 kopano dovecot: imap-login: Disconnected (auth failed, 3 attempts in 14 secs): user=<user2>, method=PLAIN, rip=192.168.0.104, lip=172.28.0.12, TLS, session=<FJg7KwyDhdPAqPpo>
Mar  1 18:59:49 kopano dovecot: auth: Error: LDAP: Can't connect to server: ldap://ldap:389
Mar  1 18:59:59 kopano dovecot: auth: Error: LDAP: Can't connect to server: ldap://ldap:389
Mar  1 19:00:09 kopano dovecot: auth: Error: LDAP: Can't connect to server: ldap://ldap:389
Mar  1 19:00:11 kopano dovecot: imap-login: Disconnected (auth failed, 3 attempts in 26 secs): user=<user2@kopano.mydomain.de>, method=PLAIN, rip=192.168.0.104, lip=172.28.0.12, TLS, session=<jDcPLAyDi9PAqPpo>
```

The error sounds like dovecot cannot connect to ldap URI. But I have double checked that via ldapsearch from within mail container. No problem at all to connect via given BindDN (readonly user and password). 
Any idea what I am missing or is this just broken for now? 
Is Demo environment missing something here?
